apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggy-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buggy-app
  template:
    metadata:
      labels:
        app: buggy-app
    spec:
      containers:
      - name: buggy-app-container
        image: https://636181284446.dkr.ecr.us-east-1.amazonaws.com/buggy-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: buggy-app
  name: buggy-app
spec:
  type: LoadBalancer
  selector:
    app: buggy-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080